/**
 * Sample Data Generator Utility
 * Generates messy and standard employee data samples for testing
 */

import { exportToCSV } from './csvWriter';
import type { DETRecord } from '../types';

/**
 * Generates messy employee data with intentionally problematic formatting
 * Includes: combined fields, missing fields, inconsistent formats
 */
export function generateMessyEmployeeData(): void {
  const messyData: Partial<DETRecord>[] = [
    // Row 1: Combined full name in one field, missing address components
    {
      record_type: 'DET',
      record_sequence: '1',
      company_id: 'COMP001',
      employee_id: '1001',
      first_name: 'John Doe', // Combined name!
      last_name: '', // Missing
      dob: '1990-05-15',
      ssn: '123-45-6789', // Missing dashes
      home_street: '123 Main St, Hanahan, SC 29410', // Combined address!
      home_city: '', // Missing
      home_state: '', // Missing
      home_zip: '', // Missing
      work_street: '456 King St',
      work_city: 'Charleston',
      work_state: 'SC',
      work_zip: '29401',
      hire_date: '11/01/2025', // Wrong format!
      original_hire_date: '2025-11-01',
      job_title: 'Software Engineer',
      department: 'Engineering',
      manager_email: 'manager@company.com',
      employee_email: 'john.doe@company.com',
      employee_phone: '(555) 010-1234', // Inconsistent format
      flsa_status: 'Exempt',
      annual_salary: '120000',
      pay_frequency: 'Bi-weekly',
      employment_type: 'Full-time',
      employee_status: 'Active',
      pay_rate_type: 'Salary',
      hours_per_week: '40',
      fed_status: 'Married',
      fed_allowances: '2',
      fed_extra_wh_per_paycheck: '0.00',
      state_code: 'SC',
      state_extra_wh_per_paycheck: '0.00',
      i9_status: 'Completed',
      e_verify_status: 'Authorized',
      dd1_routing_number: '012345678',
      dd1_account_number: '987654321',
      dd1_account_type: 'Checking',
      dd1_split_type: 'Percent',
      dd1_split_value: '100'
    },
    // Row 2: Missing required fields, inconsistent phone format
    {
      record_type: 'DET',
      record_sequence: '2',
      company_id: 'COMP001',
      employee_id: '1002',
      first_name: 'Jane',
      last_name: 'Smith',
      dob: '1995-10-20',
      ssn: 'XXX-XX-5678',
      home_street: '456 Oak Ave',
      home_city: 'Atlanta',
      home_state: 'GA',
      home_zip: '30301',
      work_street: '456 Oak Ave',
      work_city: 'Atlanta',
      work_state: 'GA',
      work_zip: '30301',
      hire_date: '2025-11-03',
      original_hire_date: '2025-11-03',
      job_title: '', // Missing required field!
      department: 'Product',
      manager_email: 'director@company.com',
      employee_email: 'jane.smith@company.com',
      employee_phone: '5550102', // No dashes
      flsa_status: 'Exempt',
      annual_salary: '140000',
      pay_frequency: 'Weekly',
      employment_type: 'Full-time',
      employee_status: 'Active',
      pay_rate_type: 'Salary',
      hours_per_week: '40',
      fed_status: 'Single',
      fed_allowances: '1',
      fed_extra_wh_per_paycheck: '0.00',
      state_code: 'GA',
      state_extra_wh_per_paycheck: '10.00',
      local_tax_code_1: 'ATL_CITY_TAX',
      i9_status: 'Completed',
      e_verify_status: 'Authorized',
      dd1_routing_number: '111111111',
      dd1_account_number: '222222222',
      dd1_account_type: 'Checking',
      dd1_split_type: 'Flat_Amount',
      dd1_split_value: '500'
      // Missing dd1_split_value would cause validation error
    },
    // Row 3: Extra whitespace, wrong date format
    {
      record_type: 'DET',
      record_sequence: '3',
      company_id: 'COMP002',
      employee_id: '1003',
      first_name: '  Peter  ', // Extra whitespace
      last_name: '  Jones  ', // Extra whitespace
      dob: '01/01/1998', // Wrong format
      ssn: 'XXX-XX-9012',
      home_street: '789 Pine Ln',
      home_city: 'Charlotte',
      home_state: 'NC',
      home_zip: '28202',
      work_street: '100 Tryon St',
      work_city: 'Charlotte',
      work_state: 'NC',
      work_zip: '28202',
      hire_date: '2025-11-04',
      original_hire_date: '2025-11-04',
      job_title: 'Sales Rep',
      department: 'Sales',
      manager_email: 'jane@company.com',
      employee_email: 'peter.jones@company.com',
      employee_phone: '555.0103', // Wrong format
      flsa_status: 'Non-Exempt',
      annual_salary: '65000',
      pay_frequency: 'Bi-weekly',
      employment_type: 'Part-time',
      employee_status: 'Active',
      pay_rate_type: 'Hourly',
      hours_per_week: '20',
      fed_status: 'Single',
      fed_allowances: '2',
      fed_extra_wh_per_paycheck: '0.00',
      state_code: 'NC',
      state_extra_wh_per_paycheck: '0.00',
      i9_status: 'Pending_Section_2', // Not ready!
      e_verify_status: 'Not_Started', // Not ready!
      // Missing required direct deposit fields
    },
    // Row 4: Combined address in work fields, missing some fields
    {
      record_type: 'DET',
      record_sequence: '4',
      company_id: 'COMP002',
      employee_id: '1004',
      first_name: 'Sarah',
      last_name: 'Williams',
      dob: '1992-03-15',
      ssn: 'XXX-XX-3456',
      home_street: '321 Elm St',
      home_city: 'Raleigh',
      home_state: 'NC',
      home_zip: '27601',
      work_street: '500 Fayetteville St, Raleigh, NC 27601', // Combined!
      work_city: '', // Missing
      work_state: '', // Missing
      work_zip: '', // Missing
      hire_date: '2025-11-05',
      original_hire_date: '2025-11-05',
      job_title: 'HR Manager',
      department: 'Human Resources',
      manager_email: 'ceo@company.com',
      employee_email: 'sarah.williams@company.com',
      employee_phone: '555-0104',
      flsa_status: 'Exempt',
      annual_salary: '95000',
      pay_frequency: 'Semi-monthly',
      employment_type: 'Full-time',
      employee_status: 'Active',
      pay_rate_type: 'Salary',
      hours_per_week: '40',
      fed_status: 'Married',
      fed_allowances: '3',
      fed_extra_wh_per_paycheck: '0.00',
      state_code: 'NC',
      state_extra_wh_per_paycheck: '0.00',
      i9_status: 'Completed',
      e_verify_status: 'Authorized',
      dd1_routing_number: '444444444',
      dd1_account_number: '555555555',
      dd1_account_type: 'Checking',
      dd1_split_type: 'Percent',
      dd1_split_value: '100'
    },
    // Row 5: Missing multiple required fields
    {
      record_type: 'DET',
      record_sequence: '5',
      company_id: 'COMP001',
      employee_id: '1005',
      first_name: 'Michael',
      last_name: 'Brown',
      dob: '1988-07-22',
      ssn: 'XXX-XX-7890',
      home_street: '654 Maple Dr',
      home_city: 'Greenville',
      home_state: 'SC',
      home_zip: '29601',
      work_street: '654 Maple Dr',
      work_city: 'Greenville',
      work_state: 'SC',
      work_zip: '29601',
      hire_date: '2025-11-06',
      original_hire_date: '2025-11-06',
      job_title: 'Data Analyst',
      department: 'Analytics',
      manager_email: 'director@company.com',
      employee_email: 'michael.brown@company.com',
      employee_phone: '555-0105',
      flsa_status: 'Exempt',
      // Missing required fields: annual_salary, pay_frequency, fed_allowances, direct deposit fields
      employment_type: 'Full-time',
      employee_status: 'Active',
      pay_rate_type: 'Salary',
      hours_per_week: '40',
      fed_status: 'Single',
      fed_extra_wh_per_paycheck: '0.00',
      state_code: 'SC',
      state_extra_wh_per_paycheck: '0.00',
      i9_status: 'Completed',
      e_verify_status: 'Authorized',
      // Missing required direct deposit fields
    }
  ];

  // Use all standard headers but data will be messy
  const headers = [
    'record_type', 'record_sequence', 'company_id',
    'employee_id', 'first_name', 'last_name', 'dob', 'ssn',
    'home_street', 'home_city', 'home_state', 'home_zip',
    'work_street', 'work_city', 'work_state', 'work_zip',
    'hire_date', 'original_hire_date', 'rehire_date', 'termination_date',
    'job_title', 'department', 'manager_email', 'employee_email', 'employee_phone',
    'flsa_status', 'annual_salary', 'pay_frequency', 'employment_type',
    'employee_status', 'pay_rate_type', 'hours_per_week',
    'fed_status', 'fed_allowances', 'fed_extra_wh_per_paycheck',
    'state_code', 'state_extra_wh_per_paycheck', 'local_tax_code_1',
    'i9_status', 'e_verify_status',
    'dd1_routing_number', 'dd1_account_number', 'dd1_account_type',
    'dd1_split_type', 'dd1_split_value',
    'dd2_routing_number', 'dd2_account_number', 'dd2_account_type',
    'union_employee', 'union_start_date', 'union_dues_amount_per_paycheck',
    'health_plan_name', 'health_deduction_per_paycheck',
    'disability_plan_code',
    'retirement_plan_type', 'retirement_contribution_percent', 'retirement_loan_repayment',
    'garnishment_type', 'garnishment_amount_per_paycheck',
    'emergency_contact_name', 'emergency_contact_phone',
    'gender', 'ethnicity', 'disability_status', 'veteran_status'
  ];

  exportToCSV(messyData as DETRecord[], 'messy_employee_data_sample.csv', headers);
}

/**
 * Generates clean, properly formatted standard employee data
 * All fields separated correctly, consistent formatting
 */
export function generateStandardEmployeeData(): void {
  const standardData: Partial<DETRecord>[] = [
    {
      record_type: 'DET',
      record_sequence: '1',
      company_id: 'COMP001',
      employee_id: '1001',
      first_name: 'John',
      last_name: 'Doe',
      dob: '1990-05-15',
      ssn: 'XXX-XX-1234',
      home_street: '123 Main St',
      home_city: 'Hanahan',
      home_state: 'SC',
      home_zip: '29410',
      work_street: '456 King St',
      work_city: 'Charleston',
      work_state: 'SC',
      work_zip: '29401',
      hire_date: '2025-11-01',
      original_hire_date: '2025-11-01',
      job_title: 'Software Engineer',
      department: 'Engineering',
      manager_email: 'manager@company.com',
      employee_email: 'john.doe@company.com',
      employee_phone: '555-0101',
      flsa_status: 'Exempt',
      annual_salary: '120000',
      pay_frequency: 'Bi-weekly',
      employment_type: 'Full-time',
      employee_status: 'Active',
      pay_rate_type: 'Salary',
      hours_per_week: '40',
      fed_status: 'Married',
      fed_allowances: '2',
      fed_extra_wh_per_paycheck: '0.00',
      state_code: 'SC',
      state_extra_wh_per_paycheck: '0.00',
      i9_status: 'Completed',
      e_verify_status: 'Authorized',
      dd1_routing_number: '012345678',
      dd1_account_number: '987654321',
      dd1_account_type: 'Checking',
      dd1_split_type: 'Percent',
      dd1_split_value: '100',
      union_employee: 'Yes',
      union_start_date: '2025-11-01',
      union_dues_amount_per_paycheck: '25.00',
      health_plan_name: 'PPO Plan',
      health_deduction_per_paycheck: '85.50',
      disability_plan_code: 'SC_SIT',
      retirement_plan_type: '401k',
      retirement_contribution_percent: '6',
      retirement_loan_repayment: '0.00',
      emergency_contact_name: 'Jane Doe',
      emergency_contact_phone: '555-1234',
      gender: 'Male',
      ethnicity: 'White',
      disability_status: 'No',
      veteran_status: 'No'
    },
    {
      record_type: 'DET',
      record_sequence: '2',
      company_id: 'COMP001',
      employee_id: '1002',
      first_name: 'Jane',
      last_name: 'Smith',
      dob: '1995-10-20',
      ssn: 'XXX-XX-5678',
      home_street: '456 Oak Ave',
      home_city: 'Atlanta',
      home_state: 'GA',
      home_zip: '30301',
      work_street: '456 Oak Ave',
      work_city: 'Atlanta',
      work_state: 'GA',
      work_zip: '30301',
      hire_date: '2025-11-03',
      original_hire_date: '2025-11-03',
      job_title: 'Product Manager',
      department: 'Product',
      manager_email: 'director@company.com',
      employee_email: 'jane.smith@company.com',
      employee_phone: '555-0102',
      flsa_status: 'Exempt',
      annual_salary: '140000',
      pay_frequency: 'Weekly',
      employment_type: 'Full-time',
      employee_status: 'Active',
      pay_rate_type: 'Salary',
      hours_per_week: '40',
      fed_status: 'Single',
      fed_allowances: '1',
      fed_extra_wh_per_paycheck: '0.00',
      state_code: 'GA',
      state_extra_wh_per_paycheck: '10.00',
      local_tax_code_1: 'ATL_CITY_TAX',
      i9_status: 'Completed',
      e_verify_status: 'Authorized',
      dd1_routing_number: '111111111',
      dd1_account_number: '222222222',
      dd1_account_type: 'Checking',
      dd1_split_type: 'Flat_Amount',
      dd1_split_value: '500',
      dd2_routing_number: '111111111',
      dd2_account_number: '333333333',
      dd2_account_type: 'Savings',
      union_employee: 'No',
      health_plan_name: 'HSA Plan',
      health_deduction_per_paycheck: '42.00',
      disability_plan_code: 'GA_SDI',
      retirement_plan_type: 'Roth 401k',
      retirement_contribution_percent: '4',
      retirement_loan_repayment: '0.00',
      emergency_contact_name: 'John Smith',
      emergency_contact_phone: '555-5678',
      gender: 'Female',
      ethnicity: 'Asian',
      disability_status: 'No',
      veteran_status: 'No'
    },
    {
      record_type: 'DET',
      record_sequence: '3',
      company_id: 'COMP002',
      employee_id: '1003',
      first_name: 'Peter',
      last_name: 'Jones',
      dob: '1998-01-01',
      ssn: 'XXX-XX-9012',
      home_street: '789 Pine Ln',
      home_city: 'Charlotte',
      home_state: 'NC',
      home_zip: '28202',
      work_street: '100 Tryon St',
      work_city: 'Charlotte',
      work_state: 'NC',
      work_zip: '28202',
      hire_date: '2025-11-04',
      original_hire_date: '2025-11-04',
      job_title: 'Sales Rep',
      department: 'Sales',
      manager_email: 'jane@company.com',
      employee_email: 'peter.jones@company.com',
      employee_phone: '555-0103',
      flsa_status: 'Non-Exempt',
      annual_salary: '65000',
      pay_frequency: 'Bi-weekly',
      employment_type: 'Part-time',
      employee_status: 'Active',
      pay_rate_type: 'Hourly',
      hours_per_week: '20',
      fed_status: 'Single',
      fed_allowances: '2',
      fed_extra_wh_per_paycheck: '0.00',
      state_code: 'NC',
      state_extra_wh_per_paycheck: '0.00',
      i9_status: 'Completed',
      e_verify_status: 'Authorized',
      dd1_routing_number: '333333333',
      dd1_account_number: '444444444',
      dd1_account_type: 'Checking',
      dd1_split_type: 'Percent',
      dd1_split_value: '100',
      union_employee: 'No',
      emergency_contact_name: 'Mark Jones',
      emergency_contact_phone: '555-4545',
      gender: 'Male',
      ethnicity: 'Black',
      disability_status: 'No',
      veteran_status: 'No'
    }
  ];

  // Use all standard headers
  const headers = [
    'record_type', 'record_sequence', 'company_id',
    'employee_id', 'first_name', 'last_name', 'dob', 'ssn',
    'home_street', 'home_city', 'home_state', 'home_zip',
    'work_street', 'work_city', 'work_state', 'work_zip',
    'hire_date', 'original_hire_date', 'rehire_date', 'termination_date',
    'job_title', 'department', 'manager_email', 'employee_email', 'employee_phone',
    'flsa_status', 'annual_salary', 'pay_frequency', 'employment_type',
    'employee_status', 'pay_rate_type', 'hours_per_week',
    'fed_status', 'fed_allowances', 'fed_extra_wh_per_paycheck',
    'state_code', 'state_extra_wh_per_paycheck', 'local_tax_code_1',
    'i9_status', 'e_verify_status',
    'dd1_routing_number', 'dd1_account_number', 'dd1_account_type',
    'dd1_split_type', 'dd1_split_value',
    'dd2_routing_number', 'dd2_account_number', 'dd2_account_type',
    'union_employee', 'union_start_date', 'union_dues_amount_per_paycheck',
    'health_plan_name', 'health_deduction_per_paycheck',
    'disability_plan_code',
    'retirement_plan_type', 'retirement_contribution_percent', 'retirement_loan_repayment',
    'garnishment_type', 'garnishment_amount_per_paycheck',
    'emergency_contact_name', 'emergency_contact_phone',
    'gender', 'ethnicity', 'disability_status', 'veteran_status'
  ];

  exportToCSV(standardData as DETRecord[], 'standard_employee_data_sample.csv', headers);
}

